Question 1:

In [6]:
b= array('B', [1,6,9,8,6])
print (b)

array('B', [1, 6, 9, 8, 6])


In [5]:
print (b.tolist())

[1, 6, 9, 8, 6]


Question 2:

In [13]:
import numpy as np

In [58]:
A= np.arange(6).reshape(2,3)

In [59]:
print(A)

[[0 1 2]
 [3 4 5]]


In [60]:
result= np.trace(A)

In [62]:
print(result)

4


Question 3:

In [ ]:
import numpy as np

In [30]:
P= np.array([[5,4],[3,8]])
if (3<4) and (3<8):
    print ('true')
else:
    print ('false')

true


Question 4:

In [ ]:
import numpy as np

In [31]:
M= np.array([[4,5],[7,6]])

In [32]:
N= np.array([[5,3],[1,3]])

In [70]:
O= np.array([[9,8],)

Question 5:

In [46]:
import numpy as np

In [55]:
X= np.random.rand(5,4)

In [56]:
print(X)

[[0.87771904 0.07676725 0.10152017 0.5167257 ]
 [0.10070777 0.04373775 0.56009894 0.10391198]
 [0.79395925 0.38986287 0.20784806 0.66749115]
 [0.83987793 0.42332317 0.4097684  0.16111142]
 [0.96010496 0.08438335 0.53709946 0.28274836]]


In [67]:
Y=X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[ 0.484536   -0.31641579 -0.29166287  0.12354266]
 [-0.10140634 -0.15837636  0.35798483 -0.09820213]
 [ 0.27916892 -0.12492747 -0.30694227  0.15270082]
 [ 0.3813577  -0.03519706 -0.04875183 -0.29740881]
 [ 0.49402093 -0.38170068  0.07101543 -0.18333568]]
